# Generated by Django 3.2.6 on 2021-08-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='fqdn',
            field=models.CharField(blank=True, help_text='FQDN', max_length=300, null=True, verbose_name='FQDN'),
        ),
        migrations.AddField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Server Name'),
        ),
        migrations.RemoveField(
            model_name='software',
            name='server',
        ),
        migrations.AddField(
            model_name='software',
            name='server',
            field=models.ManyToManyField(blank=True, to='merlink.Server', verbose_name='Server Software'),
        ),
        migrations.AlterField(
            model_name='software',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='year'),
        ),
    ]
