# Generated by Django 3.2.6 on 2021-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Software Name')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('status', models.BooleanField(default=False, verbose_name='Active')),
                ('version', models.CharField(blank=True, help_text='Version', max_length=300, null=True, verbose_name='Version')),
                ('install_date', models.CharField(blank=True, help_text='Install Date', max_length=300, null=True, verbose_name='Install Date')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Server Name')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('status', models.BooleanField(default=False, verbose_name='Active')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('fqdn', models.CharField(blank=True, help_text='FQDN', max_length=300, null=True, verbose_name='FQDN')),
                ('software', models.ManyToManyField(blank=True, to='servers.Software', verbose_name='Server Software')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ['id', 'name'],
            },
        ),
    ]
